#!/bin/sh

#fun_0{} {
echo "Введите А"
                read a
echo "Введите B"
                read b
echo "Введите С"
                read c

while [ "$a" =~  ^[1-9]+$ ] && [ "$b" =~ ^[1-9]+$] && [ "$c" =~ ^[1-9]+$] ; do
echo "A= $a, B= $b, C= $c"
done
#}
#fun_2() {
        set -x -e
#fun_0 $a $b $c

if ["$a" = "$b" -a "$b" ="$c" -a "$c" = "$a"]; then
echo "Треугольник равносторонний"
elif [["$a" = "$b" || "$c" = "$b" || "$c" = "$a" ]]; then
echo "Треугольник равнобедренный"
